name: Fetch from upstreams

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -LJO https://github.com/nftkitten/nftkitten-cli/raw/main/main
        chmod +x ./main
        ENDPOINT=https://api-mainnet.magiceden.dev/v2/collections LIMIT=500 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json collections.json  || rm .out.json
        ls -l *.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'