name: Fetch from upstreams

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        curl -LJO https://github.com/nftkitten/nftkitten-cli/raw/main/main
        chmod +x ./main
    - run: |
        curl -LJ0o .out.json --compressed 'https://api-mainnet.magiceden.io/all_collections_with_escrow_data?edge_cache=true' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://magiceden.io/' -H 'Origin: https://magiceden.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
        [ $? -eq 0 ] && mv .out.json collections.json  || rm .out.json
        git pull --no-commit origin
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        curl -LJ0o .out.json --compressed 'https://api-mainnet.magiceden.io/drops?edge_cache=true' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://magiceden.io/' -H 'Origin: https://magiceden.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
        [ $? -eq 0 ] && mv .out.json drops.json  || rm .out.json
        git pull --no-commit origin
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        curl -LJ0o .out.json --compressed 'https://api-mainnet.magiceden.io/rpc/getAggregatedCollectionMetrics?timeframe=1d&edge_cache=true' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://magiceden.io/' -H 'Origin: https://magiceden.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
        [ $? -eq 0 ] && mv .out.json collectionMetrics1d.json  || rm .out.json
        git pull --no-commit origin
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        curl -LJ0o .out.json --compressed 'https://api-mainnet.magiceden.io/rpc/getAggregatedCollectionMetrics?timeframe=7d&edge_cache=true' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://magiceden.io/' -H 'Origin: https://magiceden.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
        [ $? -eq 0 ] && mv .out.json collectionMetrics7d.json  || rm .out.json
        git pull --no-commit origin
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        curl -LJ0o .out.json --compressed 'https://api-mainnet.magiceden.io/rpc/getAggregatedCollectionMetrics?timeframe=30d&edge_cache=true' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://magiceden.io/' -H 'Origin: https://magiceden.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
        [ $? -eq 0 ] && mv .out.json collectionMetrics30d.json  || rm .out.json
        git pull --no-commit origin
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        function list() { cat collections.json | jq -r '.collections[] | .symbol + "/_" + .updatedAt + ".json"' };
        function filter() { while read i; do [ -f $i ] || echo $i; done };
        for i in $(list | filter | head -100); do mkdir -p $(dirname $i) && curl -m 30 -LJ0o .out.json --compressed 'https://api-mainnet.magiceden.dev/rpc/getCollectionEscrowStats/'$(dirname $i)'?timeframe=1d&edge_cache=true' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://magiceden.io/' -H 'Origin: https://magiceden.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' && mv .out.json $(dirname $i)'/_.json' && touch $i; done;
        find . -name '.out.json' -exec rm -rf {} \; ;
        find . -name '_.json' -size 0 -exec rm -rf {} \; ;
        git pull --no-commit origin
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
