name: Fetch from upstreams

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        curl -LJO https://github.com/nftkitten/nftkitten-cli/raw/main/main
        chmod +x ./main
    - run: |
        ENDPOINTS=https://api-mainnet.magiceden.dev/v2/launchpad/collections LIMIT=500 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json launchpad.json  || rm .out.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        ENDPOINTS=https://api-mainnet.magiceden.dev/v2/collections LIMIT=500 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json collections.json  || rm .out.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        C=https://api-mainnet.magiceden.dev/v2/collections ENDPOINTS=$(cat launchpad.json | jq -r '.[] | "$C/" + .symbol + "/stats"') ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json launchpadStats.json  || rm .out.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'
    - run: |
        C=https://api-mainnet.magiceden.dev/v2/collections ENDPOINTS=$(cat collections.json | jq -r '.[] | "$C/" + .symbol + "/stats"') ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json collectionsStats.json  || rm .out.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'