name: Fetch from upstreams

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        curl -LJO https://github.com/nftkitten/nftkitten-cli/raw/main/main
        chmod +x ./main
        ENDPOINTS=https://api-mainnet.magiceden.dev/v2/launchpad/collections LIMIT=500 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json launchpad.json  || rm .out.json
        ENDPOINTS=$(cat launchpad.json | jq -r '.[] | "https://api-mainnet.magiceden.dev/v2/collections/" + .symbol + "/listings"') LIMIT=20 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json launchpadListings.json  || rm .out.json
        ENDPOINTS=https://api-mainnet.magiceden.dev/v2/collections LIMIT=500 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json collections.json  || rm .out.json
        ENDPOINTS=$(cat collections.json | jq -r '.[] | "https://api-mainnet.magiceden.dev/v2/collections/" + .symbol + "/listings"') LIMIT=20 ./main magiceden >.out.json
        [ $? -eq 0 ] && mv .out.json collectionsListings.json  || rm .out.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '*.json'